inherit_gem:
  rubocop-discourse: default.yml

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Discourse/Plugins/NoMonkeyPatching:
  Enabled: false

Discourse/Plugins/NamespaceMethods:
  Enabled: false

AllCops:
  SuggestExtensions: false
